### ISSUE TITLE
Transition on Transform not working correctly

### ISSUE THREAD

**Issue by nothrem** [peteboere/css-crush#68] opened 2015-01-12 14:38 UTC
When I want to animate element scaling, I need to use this style:

`.animateZoom{`
`	transform: scale(1);`
`	transition: transform 0.5s ease 0.5s;`
`}`

In this definition both transform and transition keywords must be prefixed in both definitions and values:
`.animateZoom{`
`    -webkit-transform: scale(0.1);`
`    -moz-transform: scale(0.1);`
`    transform: scale(0.1);`
`    -webkit-transition: -webkit-transform 0.5s ease 0.5s;`
`    -moz-transition: -moz-transform 0.5s ease 0.5s;`
`    transition: transform 0.5s ease 0.5s;`
`}`

But CssCrush translates only the definitions, not the values:
`.animateZoom{`
`    -webkit-transform: scale(0.1);`
`    -moz-transform: scale(0.1);`
`    transform: scale(0.1);`
`    -webkit-transition: transform 0.5s ease 0.5s;` //<<missing -webkit-transform
`    -moz-transition: transform 0.5s ease 0.5s;` //<<missing -moz-transform
`    transition: transform 0.5s ease 0.5s;`
`}`

See http://stackoverflow.com/questions/13782277/css3-transforms-and-transitions-webkit

**Comment by peteboere** [comment] 2015-02-17 09:07
Dupe of #25

**Closed by peteboere** 2015-02-17 09:07 UTC
